### ISSUE TITLE
[BUG] Subprojects devDependencies aren't being "merged "

### ISSUE THREAD

**Issue by zetashift** [aws/aws-pdk#390] opened 2023-05-03 16:18 UTC
### Describe the bug

When running `pnpm projen` using a "custom project" which is a class that extends `TypeScriptAppProject`, that has dev dependencies specified, and you instantiate this class, specifying dev dependencies, the class dev deps aren't being installed in `node_modules`.

Thus during development time, errors pop up that it can't find certain binaries/deps, like in case of my repro (see reproduction steps):

`pnpm exec nx run fooy:dev` result in:

```
/bin/sh: 1: vite: not found
👾 Task "dev" failed when executing "vite dev" (cwd: /home/rishi/dev/webdev/foo/packages/fooy)
 ELIFECYCLE  Command failed with exit code 1.

 ————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Running target dev for project fooy failed

   Failed tasks:

   - fooy:dev
```

### Expected Behavior

All the dev dependencies are merged together and installed in the `node_modules` folder

### Current Behavior

`outdir` is being generated but only a part of the `devDependencies` is generated, namely the ones specified in `.projectrc.ts` and not the ones specified by the class aren't generated.

### Reproduction Steps

See: https://github.com/zetashift/pdk-pnpm-repro for the full example.

- Run ` pnpx projen new --from @aws-prototyping-sdk/nx-monorepo --packageManager pnpm`
- Create a class that inherits from TypeScriptApp, like here: https://github.com/zetashift/pdk-pnpm-repro/blob/main/FooProject.ts
- That class needs to specify a dev dependency, in this case it's `vite`.
- Use the class in your monorepo: https://github.com/zetashift/pdk-pnpm-repro/blob/main/.projenrc.ts#LL18C1-L18C1 this class should also specify some dev dependencies
- Run `pnpm project`
- You'll see in `packages/dir/node_modules` that there is no `vite` binary.

### Possible Solution

Not use a class that extends from `TypeScriptProjectApp` and just use `TypeScriptProjectApp` for everything.

### Additional Information/Context

Only using `nx-monorepo` here. Not sure if this is a projen issue (I don't think so, this used towork just fine before a PDK upgrade).

### PDK version used

@aws-prototyping-sdk/nx-monorepo: ^0.18.0

### What languages are you seeing this issue on?

Typescript

### Environment details (OS name and version, etc.)

Linux x64 and MacOS ARM64

**Comment by agdimech** [comment] 2023-05-03 21:26
Hi - sorry that this is happening.

Are you able to please provide me with a full install log as well as I want to see if any errors or warnings are being thrown.

**Comment by agdimech** [comment] 2023-05-03 23:33
OK - did some digging.

The issue is that deepMerge does not actually merge arrays, it clobbers them as per: https://github.com/projen/projen/blob/main/src/util.ts#L221

In order to achieve what you want, I recommend you don't use deep merge and instead do something like the following whenever working with arrays:

```
constructor(options: FooProjectOptions) {
    const defaultOptions = {
      srcdir: "src",
      eslint: false,
      minNodeVersion: "16.20.0",
      jest: false,
    };
    super({
      ...defaultOptions,
      ...options,
      sampleCode: false,
    });

    this.addDevDeps(
      "@sveltejs/adapter-auto",
      "@sveltejs/kit",
      "svelte",
      "tslib",
      "vite",
      "svelte-check"
    );

    ...
  }
```

This will ensure your default devDeps are added (via `this.addDevDeps`) and also the passed in DevDeps from options are just passed to the parent props.

Have tested on your fork and this definitely works as per the generated package.json in package/fooy:

```
"devDependencies": {
    "@popperjs/core": "*",
    "@sveltejs/adapter-auto": "*",
    "@sveltejs/kit": "*",
    "@types/node": "^16",
    "autoprefixer": "*",
    "classnames": "*",
    "flowbite": "*",
    "flowbite-svelte": "*",
    "npm-check-updates": "^16",
    "postcss": "*",
    "projen": "*",
    "svelte": "*",
    "svelte-check": "*",
    "tailwindcss": "*",
    "tslib": "*",
    "typescript": "*",
    "vite": "*"
  },
```

**Comment by agdimech** [comment] 2023-05-03 23:33
Please feel free to re-open if you feel this was closed in error.

**Closed as completed by agdimech** 2023-05-03 23:33 UTC
Labels: bug

**Comment by zetashift** [comment] 2023-05-04 15:19
> Please feel free to re-open if you feel this was closed in error.

Your explanation helped! I have a successful compilation now :D, thank you! `deepMerge` worked fine before so I was confused, but `addDevDeps` works better!
