### ISSUE TITLE
[DOCS] Static website loaded in Chrome becomes page unresponsive

### ISSUE THREAD

**Issue by em-xqm** [aws/aws-pdk#273] opened 2023-01-31 22:45 UTC
### Describe the issue

![image](https://user-images.githubusercontent.com/56704051/215900143-9020da9f-d912-4bd2-a153-7625f44a16a5.png)
PDK documentation website loaded in Chrome will become responsive. Has consistently occurred multiple times. Tested in firefox it took a few seconds but loaded. 

### Links

https://aws.github.io/aws-prototyping-sdk/typescript/cdk-graph/index.html
https://aws.github.io/aws-prototyping-sdk/java/open-api-gateway/index.html

**Comment by agdimech** [comment] 2023-03-26 22:10
Hi @em-xqm - are you still experiencing this issue? I am unable to reproduce this locally.

**Comment by agdimech** [comment] 2023-04-12 00:47
Closing as this has been unable to be reproduced locally and have not received updated correspondence. Please re-open if you are still experiencing this issue.

**Closed as completed by agdimech** 2023-04-12 00:47 UTC
Labels: documentation
